# Generated by Django 5.2.1 on 2025-06-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='destination',
            field=models.TextField(),
        ),
    ]
