# Generated by Django 5.1.7 on 2025-06-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_tourpackage_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_vendor_booking',
            field=models.BooleanField(default=False),
        ),
    ]
